# cloud-init.yaml
#cloud-config
package_update: true
package_upgrade: true
packages:
  - ansible
runcmd:
  - git clone https://github.com/yourusername/mediawiki-ansible-playbook.git /opt/mediawiki-ansible
  - ansible-playbook /opt/mediawiki-ansible/playbook.yml
