# playbook.yml
---
- hosts: localhost
  become: yes

  tasks:
    - name: Install SCL repository and necessary packages for RHEL 7
      yum:
        name:
          - centos-release-scl
          - httpd24-httpd
          - rh-php73
          - rh-php73-php
          - rh-php73-php-mbstring
          - rh-php73-php-mysqlnd
          - rh-php73-php-gd
          - rh-php73-php-xml
          - mariadb-server
          - mariadb
        state: present
      when: ansible_distribution_major_version == "7"

    - name: Install necessary packages for RHEL 8
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-gd
          - php-xml
          - mariadb-server
          - mariadb
          - php-mbstring
          - php-json
          - mod_ssl
          - php-intl
          - php-apcu
        state: present
      when: ansible_distribution_major_version == "8"

    - name: Start and enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation
      mysql_secure_installation:
        login_user: root
        login_password: ''
        new_password: 'YourRootPassword'
        state: present
        config_file: /root/.my.cnf

    - name: Create MediaWiki database and user
      mysql_db:
        name: wikidatabase
        state: present

    - name: Create wiki user
      mysql_user:
        name: wiki
        password: 'THISpasswordSHOULDbeCHANGED'
        priv: 'wikidatabase.*:ALL'
        state: present

    - name: Download MediaWiki tarball
      get_url:
        url: https://releases.wikimedia.org/mediawiki/1.41/mediawiki-1.41.1.tar.gz
        dest: /tmp/mediawiki-1.41.1.tar.gz

    - name: Extract MediaWiki
      unarchive:
        src: /tmp/mediawiki-1.41.1.tar.gz
        dest: /var/www
        remote_src: yes

    - name: Create symlink for MediaWiki
      file:
        src: /var/www/mediawiki-1.41.1
        dest: /var/www/mediawiki
        state: link

    - name: Set permissions for MediaWiki
      file:
        path: /var/www/mediawiki-1.41.1
        owner: apache
        group: apache
        recurse: yes

    - name: Configure Apache
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: 'DirectoryIndex index.html'
        block: |
          DocumentRoot "/var/www/mediawiki"
          <Directory "/var/www/mediawiki">
          DirectoryIndex index.html index.html.var index.php

    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted

    - name: Configure firewall for HTTP and HTTPS
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https

    - name: Restart firewalld
      systemd:
        name: firewalld
        state: restarted

    - name: Configure SELinux
      command: "restorecon -FR /var/www/mediawiki-1.41.1/"
      when: ansible_selinux.status == "enabled"
