- hosts: mediawiki
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - php-mysql
        state: present

    - name: Download MediaWiki
      get_url:
        url: "https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.0.tar.gz"
        dest: "/tmp/mediawiki.tar.gz"

    - name: Extract MediaWiki
      unarchive:
        src: "/tmp/mediawiki.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Configure MediaWiki
      template:
        src: "LocalSettings.php.j2"
        dest: "/var/www/html/mediawiki/LocalSettings.php"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

